In [2]:
import numpy as np
import time
import sys

S=range(1000)

print(sys.getsizeof(5)*len(S))

a=np.arange(1000)
print(a.size*a.itemsize)


28000
4000


In [8]:
my_1D_array = np.array([1, 2, 3, 4, 5])
print(my_1D_array.shape)

(5,)


In [10]:
my_2D_array = np.array([[1, 2],[3, 4],[6,5]])
print(my_2D_array.shape)

(3, 2)


In [13]:
change_array = np.array([1,2,3,4,5,6])
change_array.shape = (3, 2)
print(change_array)

[[1 2]
 [3 4]
 [5 6]]


In [30]:
my_array = np.array([1,2,3,4,5,6])
print(np.reshape(my_array,(3,2)))


[[1 2]
 [3 4]
 [5 6]]


# **np.reshape()**

In [33]:
#HR_Shape and Reshape
arr=[int(j) for j in input().split()]
arr=np.array(arr)
b=np.reshape(arr,(3,3))
print(b)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# **input with space of 1D array**

In [32]:
a=int(input())
b=[int(j) for j in input().split()]
print(np.array(b))

3
2 3 4
[2 3 4]


# **Transpose and Flatten**

In [34]:
my_array = np.array([[1,2,3],
                        [4,5,6]])
print(np.transpose(my_array))

[[1 4]
 [2 5]
 [3 6]]


In [35]:
my_array = np.array([[1,2,3],
                        [4,5,6]])
print(my_array.flatten())

[1 2 3 4 5 6]


# **input with space of 2D array**

In [43]:
n, m = map(int, input().split()) # taking number of rows and column

arr = np.array([input().strip().split() for _ in range(n)], int)
print(arr)

2 3
2 3
2 3
[[2 3]
 [2 3]]


In [39]:
#HR_Transpose and Flatten
n, m = map(int, input().split()) # taking number of rows and column

arr = np.array([input().strip().split() for _ in range(n)], int)

print(np.transpose(arr))
print(arr.flatten())

2 2
2 3
2 3
[[2 2]
 [3 3]]
[2 3 2 3]


# **Concatenate**

In [42]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
array_3 = np.array([7,8,9])

print(np.concatenate((array_1, array_2, array_3))) 


[1 2 3 4 5 6 7 8 9]


In [45]:
array_1 = np.array([[1,2,3],[0,0,0]])
array_2 = np.array([[0,0,0],[7,8,9]])

print(np.concatenate((array_1, array_2), axis = 1))


[[1 2 3 0 0 0]
 [0 0 0 7 8 9]]


In [47]:
#HR_Concatenate
n, m , p= map(int, input().split())
a1 = np.array([input().strip().split() for _ in range(n)], int)
a2 = np.array([input().strip().split() for _ in range(m)], int)
print(np.concatenate((a1, a2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# **Zeros and Ones**

In [50]:
print(np.zeros((1,2)))      #Default type is float

[[0. 0.]]


In [57]:
print(np.zeros((2,2), dtype = np.int))  #Type changes to int

[[0 0]
 [0 0]]


In [54]:
print(np.ones((1,2)))                  #Default type is float

[[1. 1.]]


In [56]:
print(np.ones((3,2), dtype = np.int)) #Type changes to int


[[1 1]
 [1 1]
 [1 1]]


In [62]:
#HR_Zeros and Ones
n=tuple( map(int, input().split()))
#print(n)
print(np.zeros(n, dtype = np.int))
print(np.ones(n, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [64]:
#HR_Zeros and Ones
n=list( map(int, input().split()))
#print(n)
print(np.zeros(n, dtype = np.int))
print(np.ones(n, dtype = np.int))

2 3 4
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


# Mathematics

In [9]:
#HR_Array Mathematics


n, m = map(int, input().split()) # taking number of rows and column

a = np.array([input().strip().split() for _ in range(n)], float)

b = np.array([input().strip().split() for _ in range(n)], float)

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a ** b)

1 2
1 2
3 4
[[4. 6.]]
[[-2. -2.]]
[[3. 8.]]
[[0.33333333 0.5       ]]
[[1. 2.]]
[[ 1. 16.]]


In [7]:
#HR_Eye and Identity

np.set_printoptions(legacy='1.13')

n, m = map(int, input().split()) # taking number of rows and column

print(np.eye(n, m, k = 0))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# **min**

In [13]:
my_array = np.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])
print(np.min(my_array, axis = 0))

print(np.min(my_array, axis = 1) )

print(np.min(my_array, axis = None))

print(np.min(my_array))

[1 0]
[2 3 1 0]
0
0


# **max**

In [14]:
my_array = np.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])
print(np.max(my_array, axis = 0))

print(np.max(my_array, axis = 1) )

print(np.max(my_array, axis = None))

print(np.max(my_array))

[4 7]
[5 7 3 4]
7
7


In [18]:
#HR_Min and Max
n, m = map(int, input().split()) # taking number of rows and column

a = np.array([input().strip().split() for _ in range(n)], int)

mn =np.min(a, axis = 1) 

print(np.max(mn))

1 1
1 1
1


# Sum and Prod

In [3]:
# HR_Sum and Prod
n, m = map(int, input().split()) # taking number of rows and column

a = np.array([input().strip().split() for _ in range(n)], int)

s =np.sum(a, axis = 0)

print(np.prod(s))

2 2
1 2
3 4
24


In [44]:
# HR_Mean, Var, and Std

n, m = map(int, input().split()) # taking number of rows and column

a = np.array([input().strip().split() for _ in range(n)], int)

m = np.mean(a, axis = 1)
v = np.var(a, axis = 0) 
s = np.std(a)

print(m)
print(v)
np.set_printoptions(legacy='1.13')
if s==0:
    print(0.0)
else:
    print("%.11f" % s)
#print(s)

2 2 
1 2
3 3
[ 1.5  3. ]
[ 1.    0.25]
0.82915619759


# Dot and Cross

In [16]:
#HR_Dot and Cross


n = int(input()) # taking number of rows and column

a = np.array([input().strip().split() for _ in range(n)], int)

b = np.array([input().strip().split() for _ in range(n)], int)

print(a.dot(b))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [17]:
import numpy

A = numpy.array([ 1, 2 ])
B = numpy.array([ 3, 4 ])

print(numpy.cross(A, B)  )

-2


# Inner and Outer

In [19]:
n=list( map(int, input().split()))
print(n)

2 3 4 5 6 72 3 45
[2, 3, 4, 5, 6, 72, 3, 45]


In [21]:
b=[int(j) for j in input().split()]
print(np.array(b))   # array
print(b)    # list

3 4 5 6 7 8 8 
[3 4 5 6 7 8 8]
[3, 4, 5, 6, 7, 8, 8]


In [24]:
#HR_Inner and Outer
a=np.array([int(j) for j in input().split()])

b=np.array([int(j) for j in input().split()])


print(np.inner(a,b))
print(np.outer(a,b))

0 1
2 3
3
[[0 0]
 [2 3]]
